fill_airport_list = (
	"""
		INSERT INTO Airport_City (city_name, airport_abbr) VALUES
		('Aalborg, Denmark ', 'AAL'),
		('Aalesund, Norway ', 'AES'),
		('Aarhus, Denmark - Bus service ', 'ZID'),
		('Aarhus, Denmark - Tirstrup ', 'AAR'),
		('Aasiaat, Greenland ', 'JEG'),
		('Abadan, Iran ', 'ABD'),
		('Abakan, Russia ', 'ABA'),
		('Abbotsford, BC ', 'YXX'),
		('Aberdeen, SD ', 'ABR'),
		('Aberdeen, United Kingdom ', 'ABZ'),
		('Abha, Saudi Arabia ', 'AHB'),
		('Abidjan, Cote d''Ivoire ', 'ABJ'),
		('Abilene, TX ', 'ABI'),
		('Abu Dhabi, United Arab Emirates ', 'AUH'),
		('Abu Simbel, Egypt ', 'ABS'),
		('Belleville, IL ', 'BLV'),
		('Belleville, ON - Rail service ', 'XVV'),
		('Bellingham, WA ', 'BLI'),
		('Bellona, Solomon Islands ', 'BNY'),
		('Belo Horizonte, Brazil - Pampulha ', 'PLU'),
		('Belo, Madagascar ', 'BMD'),
		('Bemidji, MN ', 'BJI'),
		('Bettles, AK ', 'BTT'),
		('Beziers, France ', 'BZR'),
		('Bhadrapur, Nepal ', 'BDP'),
		('Bhairawa, Nepal ', 'BWA'),
		('Bhamo, Myanmar ', 'BMO'),
		('Bharatpur, Nepal ', 'BHR'),
		('Bhavnagar, India ', 'BHU'),
		('Bhopal, India ', 'BHO'),
		('Bhubaneswar, India ', 'BBI'),
		('Bhuj, India ', 'BHJ'),
		('Biak, Indonesia ', 'BIK'),
		('Biarritz, France ', 'BIQ'),
		('Big Trout, ON ', 'YTL'),
		('Bikini Atoll, Marshall Islands ', 'BII'),
		('Bilbao, Spain ', 'BIO'),
		('Billings, MT ', 'BIL'),
		('Billund, Denmark ', 'BLL'),
		('Biloxi/Gulfport, MS ', 'GPT'),
		('Bima, Indonesia ', 'BMU'),
		('Bimini, Bahamas ', 'BIM'),
		('Bimini, Bahamas ', 'NSB'),
		('Binghamton, NY ', 'BGM'),
		('Bintulu, Malaysia ', 'BTU'),
		('Bintuni, Indonesia ', 'NTI'),
		('Biratragar, Nepal ', 'BIR'),
		('Birch Creek, AK ', 'KBC'),
		('Birdsville, Australia ', 'BVI'),
		('Birmingham, AL ', 'BHM'),
		('Birmingham, United Kingdom ', 'BHX'),
		('Bisha, Saudi Arabia ', 'BHH'),
		('Bishkek, Kyrgyzstan ', 'FRU'),
		('Biskra, Algeria ', 'BSK'),
		('Ceuta, Spain and Canary Islands ', 'JCU'),
		('Chadron, NE ', 'CDR'),
		('Chah-Bahar, Iran ', 'ZBR'),
		('Chalkyitsik, AK ', 'CIK'),
		('Chambery, France ', 'CMF'),
		('Chambord, QC - Rail service ', 'XCI'),
		('Champaign/Urbana, IL ', 'CMI'),
		('Chandigarh, India ', 'IXC'),
		('Chandler, QC - Rail service ', 'XDL'),
		('Changchun, China ', 'CGQ'),
		('Changde, China ', 'CGD'),
		('Changuinda, Panama ', 'CHX'),
		('Changzhou, China ', 'CZX'),
		('Chania, Greece ', 'CHQ'),
		('Chaoyang, China ', 'CHG'),
		('Chapeco, Brazil ', 'XAP'),
		('Chapleau, ON ', 'YLD'),
		('Charleston, SC ', 'CHS'),
		('Charleston, WV ', 'CRW'),
		('Charleville, Australia ', 'CTL'),
		('Daydream Is, Australia ', 'DDI'),
		('Dayton, OH ', 'DAY'),
		('Daytona Beach, FL ', 'DAB'),
		('Deauville, France ', 'DOL'),
		('Debra Marcos, Ethiopia ', 'DBM'),
		('Debra Tabor, Ethiopia ', 'DBT'),
		('Decatur, IL ', 'DEC'),
		('Deer Lake, NL ', 'YDF'),
		('Deer Lake, ON ', 'YVZ'),
		('Deering, AK ', 'DRG'),
		('Deirezzor, Syria - Al Jafrah ', 'DEZ'),
		('Del Reo, TX ', 'DRT'),
		('Delhi, India ', 'DEL'),
		('Deline, NT ', 'YWJ'),
		('Delta Junction, AK ', 'DJN'),
		('Dembidollo, Ethiopia ', 'DEM'),
		('Denham, Australia ', 'DNM'),
		('Denizli, Turkey ', 'DNZ'),
		('Denpasar Bali, Indonesia ', 'DPS'),
		('Denver, CO - International ', 'DEN'),
		('Denver, CO - Longmont Bus service ', 'QWM'),
		('Dera Ghazi, Pakistan ', 'DEA'),
		('Dera Ismail Khan, Pakistan ', 'DSK'),
		('Derby, Australia ', 'DRB'),
		('Derim, Papua New Guinea ', 'DER'),
		('Des Moines, IA ', 'DSM'),
		('Dessie, Ethiopia ', 'DSE'),
		('Detroit, MI - All airports ', 'DTT'),
		('Detroit, MI - Metro/Wayne County ', 'DTW'),
		('Devil''s Lake, ND ', 'DVL'),
		('El Portillo/Samana, Dominician Republic - El Portillo', 'EPS'),
		('El Real, Panama ', 'ELE'),
		('El Salvador, Chile ', 'ESR'),
		('El Vigia, Venezuela ', 'VIG'),
		('El Yopal, Colombia ', 'EYP'),
		('Elat, Italy ', 'ETH'),
		('Elazig, Turkey ', 'EZS'),
		('Elba Island, Italy ', 'EBA'),
		('Elcho Island, Australia ', 'ELC'),
		('Eldoret, Kenya ', 'EDL'),
		('Eleuthera Island, Bahamas ', 'ELH'),
		('Elfin Cove, AK ', 'ELV'),
		('Elim, AK ', 'ELI'),
		('Elista, Russia ', 'ESL'),
		('Elko, NV ', 'EKO'),
		('Elmira, NY ', 'ELM'),
		('Ely, MN ', 'LYU'),
		('Emae, Vanuata ', 'EAE'),
		('Embessa, Papua New Guinea ', 'EMS'),
		('Emerald, Australia ', 'EMD'),
		('Emmonak, AK ', 'EMK'),
		('Emo, Papua New Guinea ', 'EMO'),
		('Enarotali, Indonesia ', 'EWI'),
			('Freetown, Sierra Leone - Lungi Intl ', 'FNA'),
		('Fresno, CA ', 'FAT'),
		('Friedrichshafer, Germany ', 'FDH'),
		('Fuerteventura, Spain ', 'FUE'),
		('Fukue, Japan ', 'FUJ'),
		('Fukuoka, Japan ', 'FUK'),
		('Fukushima, Japan ', 'FKS'),
		('Funafuti Atol, Tuvalu ', 'FUN'),
		('Funchal, Portugal ', 'FNC'),
		('Futuna Island, Vanuatu ', 'FTA'),
		('Futuna Island, Wallis and Futuna Islands ', 'FUT'),
		('Fuyang, China ', 'FUG'),
		('Fuzhou, China ', 'FOC'),
		('Gaborone, Botswana ', 'GBE'),
		('Gafsa, Tunisia ', 'GAF'),
		('Gagnoa, Cote D''Ivoire ', 'GGN'),
		('Gainesville, FL ', 'GNV'),
		('Galapagos, Ecuador ', 'GPS'),
		('Gallivare, Sweden ', 'GEV'),
		('Gallup, NM ', 'GUP'),
		('Galway, Ireland ', 'GWY'),
		('Gamba, Gabon ', 'GAX'),
		('Halmstad, Sweden ', 'HAD'),
		('Hamburg, Germany - Fuhisbuettel ', 'HAM'),
		('Hamburg, Germany - Luebeck ', 'LBC'),
		('Hamilton Island, Australia ', 'HTI'),
		('Hamilton, New Zealand ', 'HLZ'),
		('Hamilton, ON ', 'YHM'),
		('Hammerfest, Norway ', 'HFT'),
		('Hana, HI - Island of Maui ', 'HNM'),
		('Hanapepe, HI ', 'PAK'),
		('Hancock, MI ', 'CMX'),
		('Hangzhou, China ', 'HGH'),
		('Hanimaadhoo, Maldives ', 'HAQ'),
		('Hanoi, Viet Nam - Noibai ', 'HAN'),
		('Hanover, Germany ', 'HAJ'),
		('Hanzhang, China ', 'HZG'),
		('Harare, Zimbabwe ', 'HRE'),
		('Harbin, China ', 'HRB'),
		('Hargeisa, Somolia ', 'HGA'),
		('Harlingen, TX ', 'HRL'),
		('Harrisburg, PA ', 'MDT'),
		('Harrison, AR ', 'HRO'),
		('Harstad-Narvik, Norway ', 'EVE'),
			('Jacareacanga, Brazil ', 'JCR'),
		('Jackson Hole, WY ', 'JAC'),
		('Jackson, MS ', 'JAN'),
		('Jackson, TN ', 'MKL'),
		('Jacksonville, FL ', 'JAX'),
		('Jacksonville, NC ', 'OAJ'),
		('Jacobabad, Pakistan ', 'JAG'),
		('Jacquinot Bay, Papua New Guinea ', 'JAQ'),
		('Jaipur, India ', 'JAI'),
		('Jakarta, Indonesia ', 'CGK'),
		('Jalapa, Mexico ', 'JAL'),
		('Jaluit Island, Marshall Islands ', 'UIT'),
		('Jambi. Indonesia ', 'DJB'),
		('Jamestown, ND ', 'JMS'),
		('Jamestown, NY ', 'JHW'),
		('Jamnagar, India ', 'JGA'),
		('Janakpur, Nepal ', 'JKR'),
		('Janesville, WI ', 'JVL'),
		('Jaque, Panama ', 'JQE'),
		('Jasper, AB - Rail service ', 'XDH'),
		('Jayapura, Indonesia ', 'DJJ'),
		('Jeddah, Saudi Arabia ', 'JED'),
		('Jeh, Marshall Islands ', 'JEJ'),
		('Jeju, South Korea - Jeju Airport, metro area ', 'CJU'),
		('Jerez De La Frontere, Spain ', 'XRY'),
		('Jersey, United Kingdom ', 'JER'),
		('Jessore, Bangladesh ', 'JSR'),
		('Kuala Terengganu, Malaysia ', 'TGG'),
		('Kuantan, Malaysia ', 'KUA'),
		('Kubin Island, QL, Australia ', 'KUG'),
		('Kuching, Malaysia ', 'KCH'),
		('Kudat, Malaysia ', 'KUD'),
		('Kufrah, Libya ', 'AKF'),
		('Kugaaruk, NU ', 'YBB'),
		('Kugluktuk/Coppermine, NU ', 'YCO'),
		('Kulusuk, Greenland ', 'KUS'),
		('Kumejima, Japan ', 'UEO'),
		('Kundiawa, Papau New Guinea ', 'CMU'),
		('Kuopio, Finland ', 'KUO'),
		('Kuri, Papua New Guinea ', 'KUQ'),
		('Kushiro, Japan ', 'KUH'),
		('Kutaisi, Georgia ', 'KUT'),
		('Kuujjuaq, QC ', 'YVP'),
		('Kuujjuarapik, QC ', 'YGW'),
		('Kuusamo, Finland ', 'KAO'),
		('Kuwait, Kuwait ', 'KWI'),
		('Kwajalein, Marshall Islands ', 'KWA'),
		('Kwethluk, AK ', 'KWT'),
		('Kwigillingok, AK ', 'KWK'),
		('Kyzyl, Russia ', 'KYZ'),
		('La Ceiba, Honduras ', 'LCE'),
		('La Coruna, Spain ', 'LCG'),
		('La Crosse, WI ', 'LSE'),
		('La Grande, QC ', 'YGL'),
		('La Palma, Panama ', 'PLP'),
		('La Paz, Bolivia ', 'LPB'),
			('Londrina, PR, Brazil ', 'LDB'),
		('Long Apung, Indonesia ', 'LPU'),
		('Long Banga, Malaysia ', 'LBP'),
		('Long Bawan, Indonesia ', 'LBW'),
		('Long Beach, CA ', 'LGB'),
		('Long Island, Australia ', 'HAP'),
		('Long Island/Deadmans Cay, Bahamas ', 'LGI'),
		('Long Lellang, Malaysia ', 'LGL'),
		('Long Seridan, Malaysia ', 'ODN'),
		('Longana, Vanuatu ', 'LOD'),
		('Longreach, QL, Australia ', 'LRE'),
		('Longview, TX ', 'GGG'),
		('Longyearbyen, Svalbard & Jan Mayen Island ', 'LYR'),
		('Lonorore, Vanuatu ', 'LNE'),
		('Lopez Island, WA ', 'LPS'),
		('Lord Howe Island, NS, Australia ', 'LDH'),
		('Loreto, Mexico ', 'LTO'),
		('Lorient, France ', 'LRT'),
		('Los Angeles, CA ', 'LAX'),
		('Los Cabos, Mexico ', 'SJD'),
		('Los Mochis, Mexico ', 'LMM'),
		('Losuia, Papua New Guinea ', 'LSA'),
		('Louisville, KY ', 'SDF'),
		('Lourdes/Tarbes, France ', 'LDE'),
			('Manizales, Colombia ', 'MZL'),
		('Manja, Madagascar ', 'MJA'),
		('Mankato, MN ', 'MKT'),
		('Manley Hot Springs, AK ', 'MLY'),
		('Mannheim, Germany ', 'MHG'),
		('Manokotak, AK ', 'KMO'),
		('Manokwari, Indonesia ', 'MKW'),
		('Manston, United Kingdom ', 'MSE'),
		('Manta, Ecuador ', 'MEC'),
		('Manus Island, Papua New Guinea ', 'MAS'),
		('Manzanillo, Cuba ', 'MZO'),
		('Manzanillo, Mexico ', 'ZLO'),
		('Manzini, Swaziland ', 'MTS'),
		('Mao, Chad ', 'AMO'),
		('Maota Savaii Is, Western Samoa ', 'MXS'),
		('Maputo, Mozambique ', 'MPM'),
		('Mar Del Plata, BA, Argentina ', 'MDQ'),
		('Mara Lodges, Kenya ', 'MRE'),
		('Maraba, PA, Brazil ', 'MAB'),
		('Maracaibo, Venezuela ', 'MAR'),
		('Maracay, Venezuela ', 'MYC'),
		('Mare, New Caledonia ', 'MEE'),
		('Margate, South Africa ', 'MGH'),
		('Maribor, Slovenia ', 'MBX'),
		('Mariehamn, Finland ', 'MHQ')

	"""
)